spring.application.name=TacticsAPI

spring.datasource.url=jdbc:h2:file:./data/tacticsdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true